name: payfond
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  cloud_firestore: ^4.13.6
  provider: ^6.1.1
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  http: ^1.1.2
  flutter_credit_card: ^4.0.1
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  intl: ^0.19.0
  device_preview: ^1.2.0


dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: "assets/icon/appicon.png"
  android: "launcher_icon"
  ios: true
  min_sdk_android: 21

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/appicon.png