// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDie3dux3Itl28fkNZYZGWtKntuH807drQ',
    appId: '1:348873731861:web:7a40241f697bb53bc2831c',
    messagingSenderId: '348873731861',
    projectId: 'payfond-9052f',
    authDomain: 'payfond-9052f.firebaseapp.com',
    storageBucket: 'payfond-9052f.appspot.com',
    measurementId: 'G-RZT1TB9QNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSrySLEO9-aMCWA8uu_kM5iw192k1scGk',
    appId: '1:348873731861:android:deec7026771fa6cac2831c',
    messagingSenderId: '348873731861',
    projectId: 'payfond-9052f',
    storageBucket: 'payfond-9052f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLR0-m-FRDxao1UJ5PV919VO6E1uu3LFw',
    appId: '1:348873731861:ios:6894999138050130c2831c',
    messagingSenderId: '348873731861',
    projectId: 'payfond-9052f',
    storageBucket: 'payfond-9052f.appspot.com',
    iosBundleId: 'com.payfond.payfond',
  );
}
